services:
  mysql:
    container_name: DBTechEventsRecommender
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - recommendation-network

  phpmyadmin:
    container_name: phpRecommendation
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    networks:
      - recommendation-network

  backend:
    container_name: backend_recommendation
    build:
      context: ../backend # Ajuste aqui para apontar para a pasta do backend
      dockerfile: Dockerfile
      args:
        - VERSION=v1
    volumes:
      - ../backend/:/app/ # Ajuste o caminho para o volume
      - /app/node_modules
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    networks:
      - recommendation-network

  frontend:
    container_name: frontend_recommentation
    build:
      context: ../frontend # Ajuste aqui para apontar para a pasta do frontend
      dockerfile: Dockerfile
      args:
        - VERSION=v1
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ../frontend/:/app/ # Ajuste o caminho para o volume
      - /app/node_modules
      - /app/.next
    networks:
      - recommendation-network

networks:
  recommendation-network:
    driver: bridge
volumes:
  mysql_data:
  mysql_config:
